agregar metodo getUserInfo
janis-commerce/oauth-native pull request #5
Opened 2023-10-25 22:29 UTC by dam788

**LINK DE TICKET:**

https://janiscommerce.atlassian.net/browse/APPSRN-230

**LINK DE SUBTAREA:**

https://janiscommerce.atlassian.net/browse/APPSRN-234

**DESCRIPCIÓN DEL REQUERIMIENTO:**

**Contexto**

En muchos eventos necesitamos obtener info del usuario y hoy estamos todo usandolo por el pkg oauth. El problema de esto es que es un hook y en varias ocasiones necesitamos obtener la info fuera del contexto de react. 

**Necesidad**

Dado que aun no tenemos en claro como vamos a encarar el uso de async storage, vamos  a ir por el camino de tener un método que nos brinde la información del usuario sin depender si estamos en el contexto de la libreria o no.

_"Se necesita tener un metodo por ejemplo **getUserInfo** que devuelva informacion de usuario para el uso de **analyticis** y **crashlytics**"_

**DESCRIPCIÓN DE LA SOLUCIÓN:**

- se creó una función de utilidad llamada **getUserInfo** _(es una función asíncrona)_ que trae el token desde localStorage y desencripta la data del usuario (no trae ningún token) y lo devuelve en el siguiente formato:

```
{
  "appClientId": "6bc6b92e-6283-4ad0-939a-8f16072d2e7f",
  "aud": "6bc6b92e-6283-4ad0-939a-8f16072d2e7f",
  "createdAt": "2020-12-14T18:45:28.306Z",
  "email": "fernando.colom@janis.im",
  "exp": 1697285104,
  "family_name": "Colom",
  "given_name": "Fernando",
  "iat": 1697112304,
  "images": {
    "big": "https://www.gravatar.com/avatar/034caa1d46010b8624d1b8cffaee9a88?d=404&s=512",
    "original": "https://www.gravatar.com/avatar/034caa1d46010b8624d1b8cffaee9a88?d=404",
    "thumbnail": "https://www.gravatar.com/avatar/034caa1d46010b8624d1b8cffaee9a88?d=404&s=36",
    "url": "https://www.gravatar.com/avatar/034caa1d46010b8624d1b8cffaee9a88?d=404&s=36"
  },
  "isDev": true,
  "iss": "https://id.janisdev.in",
  "locale": "en-US",
  "mainColor": "#e70c6e",
  "name": "Fernando Colom",
  "profileName": "Admin",
  "refId": null,
  "secondaryColor": "#fbfaf8",
  "sub": "5fd7b2c8d71fb1e2743bb64e",
  "tcode": "fizzmodarg",
  "tcurrency": "ARS",
  "tcurrencyDisplay": "symbol",
  "tid": "631fab63f3f96415abfeabd8",
  "timage": "https://cdn.id.janisdev.in/client-images/631fab63f3f96415abfeabd8/b25d5d55-52a5-41f8-bf22-43fc0963c875.png",
  "tname": "Fizzmod",
  "updated_at": 1697053475
}
```

**CÓMO SE PUEDE PROBAR?**

1. Entramos a la rama **APPSRN-234-agregar-metodo-get-usernfo** en **@janis-commerce/oauth-native**
2. En consola tiramos **yalc push && yalc publish** 
3. En el repo de nuestra app tiramos **yalc add @janiscommerce/oauth-native** y npm i
4. En la página home agregamos lo siguiente:

```
  const {getUserInfo} = useOauthData();
  
  ...
  
  const initUserInfo = async () => {
    const [userInfo, userInfoError] = await asyncWrap(getUserInfo());

    if (userInfoError) {
      return console.log({userInfoError})
    }
    return console.log({userInfo})
  }

  useEffect(() => {
    initUserInfo();
  }, [])
```

**SCREENSHOTS:**

**DATOS EXTRA A TENER EN CUENTA:**

CHANGELOG:

El dev debera modificar el changelog ya con el pr.

Pasos para realizar por el dev encargado de ejecutar merge y push a master

Cambiar version en package.json

Guardar cambios

Ejecutar git tag -a v[version] -m "mensaje"

Ejecutar git push origin master --follow-tags

2023-10-26 22:18 UTC, WilliamSaya-lvl30 approved these changes

2023-10-26 22:23 UTC, WilliamSaya-lvl30 requested changes
En el requerimiento especifica que la funcion se pueda usar fuera del contexto de react, exportar desde el index esta función para poder usarla independientemente

2023-10-27 19:01 UTC, WilliamSaya-lvl30 approved these changes

2023-10-30 18:05 UTC, GonzaFran approved these changes

2023-11-01 17:59 UTC, christian97dd requested changes
dejé unos comentarios

2023-11-01 17:59 UTC, christian97dd commented on src/utils/getUserInfo.js
> +    const getStorageTokens = await AsyncStorage.getItem(keys.OAUTH_TOKENS_KEY);
fijate que para hacer esto, ya hay una funcion que se llama getTokensCache. Nos va a servír usar la función ya que si por x motivo el día de mañana tenemos que cambiar las keys que guardamos en async storage, solo cambiemos la función y sigue todo ok

2023-11-01 17:59 UTC, christian97dd commented on src/utils/getUserInfo.js
> +    if (!Object.keys(oauthTokens).length) throw Error('cant get oauth tokens');
acá te faltó crear una nueva instancia de la clase error (osea throw new Error('...'))

2023-11-01 17:59 UTC, christian97dd commented on src/utils/getUserInfo.js
> +    if (!idToken) throw Error('cant get id token');
en este caso lo mismo que lo de arriba

2023-11-02 19:25 UTC, dam788 commented on src/utils/getUserInfo.js
> +    if (!Object.keys(oauthTokens).length) throw Error('cant get oauth tokens');
corregido

2023-11-02 19:25 UTC, dam788 commented on src/utils/getUserInfo.js
> +    if (!idToken) throw Error('cant get id token');
corregido

2023-11-03 13:38 UTC, merged